# Generated by Django 4.1.5 on 2023-02-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_mailing_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientsToMailing',
        ),
    ]
