# Generated by Django 4.1.5 on 2023-02-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_delete_clientstomailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='mails.client'),
        ),
    ]
